controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - gripper_fake_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
      - gripper_finger2_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: right_up